### ISSUE TITLE
Link to USDL broken

### ISSUE THREAD

**Issue by koppor** [linked-usdl/linked-usdl.github.com#1]
The link to USDL (http://www.internet-of-services.de/index.php?id=288&L=0) is broken: The domain has been grabbed.

**Comment by drleidig** [comment]
Thats true.

You may find informstion about USDL at

https://github.com/linked-usdl

Or
http://linked-usdl.org/

**Comment by koppor** [comment]
IMHO the link should be fixed on _all_ pages and material where it is used. It should point to information about other versions of USDL. Reason why there should be no broken link: People browsing the web for information typically click on links and do not search issue trackers for bugs regarding the link. Furthermore, people might want to know the differences about USDL-alpha, [W3C's USDL](http://www.w3.org/2005/Incubator/usdl/) and linked USDL.

Is the reference to [Barros, A., Oberle, D.:  Handbook of Service Description: USDL and Its Methods.
Springer](https://en.wikipedia.org/wiki/Special:BookSources/1489998977) the right one? Wikipedia cannot be used, as there is only [a German page](https://de.wikipedia.org/wiki/Unified_Service_Description_Language) and a page explaining the acronym onle ([USDL](https://en.wikipedia.org/wiki/USDL)). Or should [Jorge's presentation](http://de.slideshare.net/JorgeCardoso4/l07-linkedusdl) be linked? Especially, slide 9 provides some links to other USDL versions. OK, the first link is broken, too.

Affected are at least
- http://linked-usdl.github.io/
- http://linked-usdl.org/
- https://github.com/linked-usdl/usdl-core/blob/master/README.md
